[package]
name = "executor"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "executor"
path = "src/bin/main.rs"

[lib]
name = "executor"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
duct = "0.13"
serde_json = "1.0"
toml = "0.5"
structopt = { version = "0.3", default-features = false }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
debug = false
rpath = false
debug-assertions = false
