kind = "host"
name = "linux-pipeline"

[platform]
os = "linux"
arch = "amd64"

[[step]]
name = "test0"
env = { SERVER_1 = "ONE", SERVER_2 = "TWO" }
script = "pwd && echo $SERVER_1 && echo $SERVER_2"

[[step]]
name = "test1"
env = { SERVER_3 = "THREE", SERVER_4 = "FOUR" }
script = [
    "echo abc",
    "for i in {1..10}; do echo $i",
    "sleep 0.025 && echo 000",
    "done",
    "echo xyz",
    "for i in {1..10}; do echo $i",
    "sleep 0.025 && echo 111",
    "done",
    "echo $SERVER_3",
    "echo $SERVER_4",
]

[[step]]
name = "test2"
script = '''
    echo abc
    for i in {1..10}; do
        echo $i
        sleep 0.025 && echo 000
    done
    echo xyz
    for i in {1..10}; do
        echo $i
        sleep 0.025
        echo 111
    done
'''

# [trigger]
# event = ["push", "pull_request"]
# branch = ["master", "develop", "feature/*", "bugfix/*", "hotfix/*"]
