kind = "host"
name = "production"

[platform]
os = "linux"
arch = "amd64"

[[step]]
name = "prod0"
# image = "joseluisq/rust-linux-darwin-builder:1.55.0"
env = { SERVER_1 = "prod_ONE", SERVER_2 = "prod_TWO" }
script = "uname -a && echo $SERVER_1 && echo $SERVER_2"

[[step]]
name = "prod1"
# image = "joseluisq/rust-linux-darwin-builder:1.55.0"
env = { SERVER_3 = "prod_THREE", SERVER_4 = "prod_FOUR" }
script = [
    "echo abc",
    "for i in {1..10}; do echo $i",
    "sleep 0.025 && echo 000",
    "done",
    "echo xyz",
    "for i in {1..10}; do echo $i",
    "sleep 0.025 && echo 111",
    "done",
    "echo $SERVER_3",
    "echo $SERVER_4",
]
